---
title: "Crappy Data Picker"
author: "Michaja Pehl"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
mrindustry_version <- installed.packages() %>% 
    as_tibble() %>% 
    filter('mrindustry' == Package) %>% 
    pull('Version') %>% 
    as.numeric_version()

stopifnot(as.numeric_version('0.10.0.9001') == mrindustry_version)
library(madrat, quietly = TRUE)
library(mrindustry)

setConfig(forcecache = TRUE,
                  outputfolder = './',
                  .verbose = FALSE)

# following <- function(...) 
# {
#     list(...) |>
#         unlist() |>
#         lapply(madrat::getDependencies, direction = 'out', self = TRUE) |>
#         lapply(getElement, name = 'func') |>
#         unlist(use.names = FALSE) |>
#         unique()
# }
# 
# setConfig(ignorecache = suppressWarnings(following('readUNIDO')))
```

```{r get data}
INDSTAT2 <- readSource('UNIDO', 'INDSTAT2', convert = FALSE) %>% 
    convertUNIDO('INDSTAT2', exclude = FALSE)

INDSTAT3 <- readSource('UNIDO', 'INDSTAT3', convert = FALSE) %>% 
    convertUNIDO('INDSTAT3', exclude = FALSE)

INDSTAT4 <- readSource('UNIDO', 'INDSTAT4', convert = FALSE) %>% 
    convertUNIDO('INDSTAT4', exclude = FALSE)

exclusions <- readSource('UNIDO', 'INDSTAT2', convert = FALSE) %>% 
    convertUNIDO('INDSTAT2', exclude = 'return')
```

```{r plot, results = 'asis'}
regionmapping <- toolGetMapping('regionmapping_21_EU11-columnname.csv',
                                'regional') %>% 
    as_tibble() %>% 
    select('iso3c' = 2, 'region' = 3)

filter_region <- function(d, r)
{
    semi_join(d, regionmapping %>% filter(r == region), 'iso3c')
}

for (s in unique(exclusions$subsector)) {
    cat('\n\n# ', s, '\n')
    for (r in sort(unique(regionmapping$region))) {
        cat('\n\n## ', r, '\n')
      
        p <- ggplot() +
            geom_ribbon(
                data = exclusions %>% 
                    filter_region(r) %>% 
                    filter(s == subsector) %>%
                    arrange(iso3c, subsector, year) %>%
                    group_by(iso3c, subsector) %>%
                    mutate(group_id = cumsum(c(1, diff(year) != 1))) %>%
                    group_by(group_id, .add = TRUE) %>%
                    nest() %>% 
                    mutate(data = map(data, \(df) {
                        df %>% 
                            mutate(year = case_when(
                                min(year) == year ~ year - 0.3,
                                max(year) == year ~ year + 0.3,
                                TRUE              ~ year))
                        })) %>%
                    unnest('data'),
                mapping = aes(x = year, ymin = 0, ymax = Inf, group = group_id,
                              fill = 'INDSTAT2 excluded'),
                alpha = 0.3) +
            scale_fill_manual(values = c('INDSTAT2 excluded' = 'darkgrey'),
                              name = NULL) +
            geom_point(
                data = bind_rows(
                    INDSTAT4 %>% 
                        as_tibble() %>% 
                        mutate(version = 'INDSTAT4'),
                    
                    INDSTAT3 %>% 
                        as_tibble() %>% 
                        mutate(version = 'INDSTAT3'),
            
                    INDSTAT2 %>% 
                        as_tibble() %>% 
                        mutate(version = 'INDSTAT2')) %>% 
                  semi_join(regionmapping %>% filter(r == region), 'iso3c') %>% 
                  filter(s == subsector,
                         !is.na(value)),
                mapping = aes(x = year, y = value, colour = version,
                              shape = version),
                size = 3) +
            scale_colour_discrete(name = NULL) +
            scale_shape_manual(values = c('INDSTAT2' = 'o',
                                          'INDSTAT3' = 'x',
                                          'INDSTAT4' = '+'),
                                          name = NULL) +
            facet_wrap(vars(iso3c), scales = 'free') +
            labs(x = NULL, y = NULL) +
            theme_minimal()
        
        plot(p)
    }
}
```
